namespace: app
image:
  backend: "<REGISTRY>/catalog-back:latest"
  frontend: "<REGISTRY>/nuxt-front:latest"
replicaCount: 2
backend:
  env:
    DB_HOST: "catalog-postgres.rds.local"
    DB_PORT: "5432"
    DB_NAME: "catalog"
    DB_USER: "catalog"
    DB_PASSWORD: "change-me"
frontend:
  publicApiBase: "/api"
ingress:
  host: "app.dev.example.com"
  tlsArn: "arn:aws:acm:..."
