apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-back
  namespace: e2e
spec:
  replicas: 2
  selector:
    matchLabels: { app: catalog-back }
  template:
    metadata:
      labels: { app: catalog-back }
    spec:
      containers:
        - name: catalog-back
          image: REPLACE_REGISTRY/catalog-back:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-back
  namespace: e2e
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: catalog-back
