apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-front
  namespace: e2e
spec:
  replicas: 2
  selector:
    matchLabels: { app: nuxt-front }
  template:
    metadata:
      labels: { app: nuxt-front }
    spec:
      containers:
        - name: nuxt-front
          image: REPLACE_REGISTRY/nuxt-front:latest
          ports:
            - containerPort: 3000
          env:
            - name: NITRO_PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-front
  namespace: e2e
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nuxt-front
